### PR TITLE
Allowing run on any 6.x.x node version

### PR DESCRIPTION
**Pull request by caio-ribeiro-pereira**
Allowing run on any 6.x.x node version

I have to do it, because I'm using 6.2.1 and I can't install it.

### CODE REVIEW

**Comment by JakeSidSmith** [comment]
With what are you installing react-fastclick?

**Comment by caio-ribeiro-pereira** [comment]
I'm using Webpack, and I can't install via npm because I'm using node 6.2.1.
And this fixed version will block installations from node 6.9.5 and 7.x.x too.

**Comment by JakeSidSmith** [comment]
I'm running node `6.2.1` on one of my projects & I can install react-fastclick fine there.
What command are you running, and what error are you getting?

**Comment by caio-ribeiro-pereira** [comment]
Well, I'm using yarn, and when I run `yarn add react-fastclick` it cause this error:

``` bash
yarn add v0.16.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error react-fastclick@3.0.0: The engine "node" is incompatible with this module. Expected version "6.9.4".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by JakeSidSmith** [comment]
I'm not certain, but I think this is an issue with yarn not allowing the node engine definition at all.

Related issue here: https://github.com/JakeSidSmith/react-fastclick/issues/45

Could you give the suggestion in that issue a go? Would be good to move this conversation there also.

**Comment by JakeSidSmith** [comment]
Following discussion on #45 I have set the node engine to `*` in #47. Releasing in a second.

**Comment by caio-ribeiro-pereira** [comment]
Thanks!

**Pull request closed without merging**
