### PR TITLE
Fix bleed to other elements

### LINKED ISSUE #29: Click event propagates to a wrong element
When user clicks an element that causes re-render (e.g. react-route change) element that appears after the re-render right under the tapped position receives a click event too.

### LINKED ISSUE #34: unexpected page reload when using with react router
react router 2.3
ios 9.1
longpress on link like this will reload page

`<Link style={{ paddingBottom: 8 }} className={className} key={key} to={'/' + classDef.path + '/' + key} >`

### LINKED ISSUE #48: select and input in the handleType method did not prevent the default event
A page, if there are more than one select element, when clicking on one of the select, will cause the other select elements are clicked

https://github.com/JakeSidSmith/react-fastclick/blob/master/src/index.js#L47

Solution：

Input and select Add to prevent default events

Code: 

  var handleType = {

    input: function (event) {
      focus(event);
      **event. preventDefault();**
      event.stopPropagation();
    },
    textarea: function (event) {
      focus(event);
      event.stopPropagation();
    },
    select: function (event) {
      focus(event);
      **event. preventDefault();**
      event.stopPropagation();
    },

### PR DESCRIPTION
**Pull request by JakeSidSmith**
I have published an alpha version `3.0.2-alpha.1` for testing before release.

If you could please try out this alpha version & let me know on this PR if it has fixed your issue (please provide issue number).

Fixes #29 
Fixes #33 

Possibly fixes #34 ?
Possibly fixes #48 ?

### CODE REVIEW

**Comment by nealoke** [comment]
@JakeSidSmith I would like to test this but i'm to noob to figure out how to download this pull request. Is there a possibility to `npm install` this pull? Sorry for the lack of experience here :/

**Comment by JakeSidSmith** [comment]
Yup. It's on npm as `3.0.2-alpha.1`. Just update the version in your `package.json`, clear from your `node_modules` and `npm install`. :)

**Comment by nealoke** [comment]
Great, I'll test this the either today or tomorrow, thanks!

**Comment by nealoke** [comment]
@JakeSidSmith so sorry for the late follow up. 

I tested with the case provided from @gomo and that is definitly resolved. The only thing that is still happening (in my application) is that for whatever reason the click is being blocked but the keyboard still pops up. (I'm not sure that `react-fastclick` is the cause though.

Thanks and nice work @JakeSidSmith !

**Comment by JakeSidSmith** [comment]
@nealoke on mobile (Android or iOS)?
You want to tap an input, but not have the keyboard open?
Have you tried `event.preventDefault()` in the `onClick`?
Or in `onTouchStart`?

**Comment by nealoke** [comment]
@JakeSidSmith I'm not sure what fixed it but I guess it had something to do with my popup styling (weird though). But can't seem to reproduce it anymore. So all good for me 👍 :)

I tested the test case of @gomo on both IOS and Android (via browserstack)

**Comment by JakeSidSmith** [comment]
Guess I'll release this and see how it goes then. :)

**Comment by zhengzhiqiang** [comment]
problem

@JakeSidSmith When I use version 3.0.1, it will bleed to another element, so I upgrade to 3.0.2, then I find another problem: when I click an input element, the input will blur.

It happens on iphone devices, 6ps happened always.

**Pull request merged**
