### PR TITLE
React 0.14 support

### PR DESCRIPTION
**Pull request by JakeSidSmith**
Add `"react-fastclick": "git://github.com/jakesidsmith/react-fastclick.git#react-0.14-support"` to your dependencies for testing.

### CODE REVIEW

**Comment by JakeSidSmith** [comment]
This seems to cause issues with input focussing & standard anchor links. Will need to take another look.

**Comment by JakeSidSmith** [comment]
Events triggered on tap (when not preventing default).

```
[Log] topTouchStart
[Log] Event: null // made it passed SyntheticUIEvent.getPooled
[Log] topTouchEnd
[Log] Event type: touchend // made it passed SyntheticUIEvent.getPooled
[Log] topMouseMove
[Log] topMouseDown
[Log] topMouseUp
[Log] topClick
[Log] topSelectionChange
```

**Comment by naps62** [comment]
@JakeSidSmith I'm trying to use this branch without success
Using react 0.14.3, and importing like this:

```
require('react-fastclick');
import React form 'react';
```

on a desktop computer, it runs fine (although there's way to test if fastclick is working, AFAIK)
when opening the exact same page on my Android tablet, I get this error in the inspector:

> Uncaught Error: Invariant Violation: EventPluginHub: More than one plugin attempted to publish the same event name, `click`.

Is this a known issue? Any workarounds at this point?

**Comment by JakeSidSmith** [comment]
That's weird. I hadn't experienced that. I'm still brainstorming a better way to handle 0.14, as this solution seems to have several issues.

I have a few ideas, just need to get some time to implement & test them.

**Pull request closed without merging**
